drop view if exists "public"."companies_summary";


  create table "public"."industries" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "segment" text not null
      );


alter table "public"."industries" enable row level security;

alter table "public"."companies" add column "industry_id" bigint;

CREATE UNIQUE INDEX industries_name_key ON public.industries USING btree (name);

CREATE UNIQUE INDEX industries_pkey ON public.industries USING btree (id);

alter table "public"."industries" add constraint "industries_pkey" PRIMARY KEY using index "industries_pkey";

alter table "public"."companies" add constraint "companies_industry_id_fkey" FOREIGN KEY (industry_id) REFERENCES public.industries(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."companies" validate constraint "companies_industry_id_fkey";

alter table "public"."industries" add constraint "industries_name_key" UNIQUE using index "industries_name_key";

create or replace view "public"."companies_summary" with (security_invoker = on) as  SELECT c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.industry_id,
    count(DISTINCT d.id) AS nb_deals,
    count(DISTINCT co.id) AS nb_contacts
   FROM ((public.companies c
     LEFT JOIN public.deals d ON ((c.id = d.company_id)))
     LEFT JOIN public.contacts co ON ((c.id = co.company_id)))
  GROUP BY c.id;

insert into public.industries (name, segment) values
    ('Flooring', 'Trades & Home Services'),
    ('HVAC', 'Trades & Home Services'),
    ('Fitness Studio', 'Health & Personal Services'),
    ('Telecommunications', 'Other');


grant delete on table "public"."industries" to "anon";

grant insert on table "public"."industries" to "anon";

grant references on table "public"."industries" to "anon";

grant select on table "public"."industries" to "anon";

grant trigger on table "public"."industries" to "anon";

grant truncate on table "public"."industries" to "anon";

grant update on table "public"."industries" to "anon";

grant delete on table "public"."industries" to "authenticated";

grant insert on table "public"."industries" to "authenticated";

grant references on table "public"."industries" to "authenticated";

grant select on table "public"."industries" to "authenticated";

grant trigger on table "public"."industries" to "authenticated";

grant truncate on table "public"."industries" to "authenticated";

grant update on table "public"."industries" to "authenticated";

grant delete on table "public"."industries" to "service_role";

grant insert on table "public"."industries" to "service_role";

grant references on table "public"."industries" to "service_role";

grant select on table "public"."industries" to "service_role";

grant trigger on table "public"."industries" to "service_role";

grant truncate on table "public"."industries" to "service_role";

grant update on table "public"."industries" to "service_role";


  create policy "Enable delete for authenticated users only"
  on "public"."industries"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."industries"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."industries"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."industries"
  as permissive
  for update
  to authenticated
using (true);



